ARG VIRTUAL_ENV=/opt/venv
FROM ubuntu:22.04
SHELL ["/bin/bash", "-c"]
ARG VIRTUAL_ENV

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
	apt-get install --no-install-recommends -y \
        dos2unix \
        ca-certificates \
        file \
        locales \
        git \
        build-essential \
        cmake \
        ninja-build gperf \
        device-tree-compiler \
        wget \
        curl \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        xz-utils \
        dos2unix \
        vim \
        nano \
        mc \
        openssh-server

ENV VIRTUAL_ENV=${VIRTUAL_ENV}
RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

# Install west
RUN python3 -m pip install --no-cache-dir west

# Clean up stale packages
RUN apt-get clean -y && \
	apt-get autoremove --purge -y && \
	rm -rf /var/lib/apt/lists/*

RUN git clone -b release/0.6 https://github.com/pytorch/executorch.git && \
    cd executorch && \
    python3 -m venv .venv && \
    source .venv/bin/activate && \
    python3 -m pip install --upgrade pip && \
    ./install_executorch.sh
