ARG VIRTUAL_ENV=/opt/venv
ARG PASSWORD="zephyr"
FROM ubuntu:22.04
SHELL ["/bin/bash", "-c"]
ARG VIRTUAL_ENV
ARG PASSWORD
ARG TARGETARCH

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && \
        apt-get install --no-install-recommends -y \
        dos2unix \
        ca-certificates \
        file \
        locales \
        git \
        build-essential \
        cmake \
        ninja-build gperf \
        device-tree-compiler \
        wget \
        curl \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        xz-utils \
        dos2unix \
        vim \
        nano \
        mc \
        openssh-server

# Install additional required software for Zephyr
RUN apt install --no-install-recommends -y ccache \
    dfu-util \
    python3-setuptools \
    python3-tk \
    python3-wheel \
    make \
    gcc \
    libsdl2-dev \
    libmagic1 \
    xterm \
    telnet \
    net-tools

RUN if [ "$TARGETARCH" = "amd64" ]; then \
        apt install --no-install-recommends -y gcc-multilib g++-multilib; \
    fi

RUN if [ "$TARGETARCH" = "arm64" ]; then \
    apt install --no-install-recommends -y libc6-amd64-cross; \
    ln -s /usr/x86_64-linux-gnu/lib64/ /lib64; \
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/lib64:/usr/x86_64-linux-gnu/lib"; \
fi

ENV VIRTUAL_ENV=${VIRTUAL_ENV}
RUN python3 -m venv ${VIRTUAL_ENV}
ENV PATH="${VIRTUAL_ENV}/bin:$PATH"

# Install west
RUN python3 -m pip install --no-cache-dir west

# Clean up stale packages
RUN apt-get clean -y && \
        apt-get autoremove --purge -y && \
        rm -rf /var/lib/apt/lists/*


# Create a non-root user and group
RUN useradd -d /home/zephyruser -m -s /bin/bash zephyruser
# Switch to the non-root user
USER zephyruser

# Download and install executorch
RUN cd /home/zephyruser && git clone https://github.com/BujSet/executorch.git && \
    cd executorch && \
    # git switch -c arm-zphyr-eabi origin/arm-zphyr-eabi && \
    python3 -m venv .venv && \
    source .venv/bin/activate && \
    python3 -m pip install --upgrade pip && \
    ./install_executorch.sh && \
    git submodule sync && \
    git submodule update --init --recursive && \
    mkdir cmake-out && cd cmake-out && cmake .. && cd ../ && \
    cmake --build cmake-out -j9

# kitware script must be run as root user for some reason
USER root
RUN cd /home/zephyruser/ && wget https://apt.kitware.com/kitware-archive.sh && \
    chmod +x kitware-archive.sh && \
    ./kitware-archive.sh

USER zephyruser
RUN cd /home/zephyruser/ && \
    wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.0/zephyr-sdk-0.16.0_linux-x86_64.tar.xz && \
    tar -xf zephyr-sdk-0.16.0_linux-x86_64.tar.xz

# Install zephyr SDK, must be run as non-root user
USER zephyruser
RUN cd /home/zephyruser/ && \
    source /home/zephyruser/executorch/.venv/bin/activate && \
    pip install west && \
    west init zephyrproject

RUN cd /home/zephyruser/zephyrproject && \
    source /home/zephyruser/executorch/.venv/bin/activate && \
    west update && \
    west zephyr-export

RUN cd /home/zephyruser/zephyrproject && \
    source /home/zephyruser/executorch/.venv/bin/activate && \
    pip install -r zephyr/scripts/requirements.txt

RUN cd /home/zephyruser/zephyrproject/zephyr && \
    source /home/zephyruser/executorch/.venv/bin/activate && \
    west build -p auto -b mps3/corstone300/an547 samples/hello_world

# Install arm FVP, must be run as non-root user
USER zephyruser
RUN cd /home/zephyruser/executorch && \
    source .venv/bin/activate && \
    git config --global user.email "zephyruser@gmail.com" && \
    git config --global user.name "ZephyrUser" && \
    ./examples/arm/setup.sh --i-agree-to-the-contained-eula && \
    source  examples/arm/ethos-u-scratch/setup_path.sh && \
    ./examples/arm/setup.sh --i-agree-to-the-contained-eula

ENV ZEPHYR_TOOLCHAIN_VARIANT=zephyr
ENV ZEPHYR_SDK_INSTALL_DIR=/home/zephyruser/zephyr-sdk-0.16.0
USER zephyruser
